language: node_js
node_js:
- '6.3'
- '5.11'
- '0.12'
- iojs
cache:
  directories:
  - node_modules
before_install:
- rvm install 2.2.2
- gem install github_changelog_generator
install:
- npm install
script:
- npm run lint && npm run test
after_success:
- bash curl https://gist.githubusercontent.com/webPapaya/65651d31f538dbe3f64a65e7b77de551/raw/5324e468917fb0cc7b625c9eddf871ad160a5441/deploy-changelog.sh > deploy-changelog.sh && chmod u+x deploy-changelog.sh && ./deploy-changelog.sh
env:
  global:
  - CHANGELOG_BRANCH=master
  - CHANGELOG_NAME=braumeister
  - CHANGELOG_EMAIL=braumeister@crewmeister.com
  - secure: UNAMBURaf7y43+Gp7Ev7l3rennt1M2YrGRhixzPCIlmusTUOPOPDnHGGQOAv8AzCbgN+OTkE2uXtBLQjCz6/+MtjGJdf4IR2S6Il4PXuwvLXYPdCYaXAlI0t1cYz7V7sjxMsSzEwfDdQT2nG4xCloAhkILeE3ieOQQbO2k3zR8etASJusZHTJs0GztOQpqjppkfwXZ+IMmg1OAA/n7t4L8lWpqErNEbubZAmk/N+QlIaEfDqnOkKNivdXE3r0QeF/zUbTzwaSgB8muc54BmMZUTCA32DBV/Ran2q+aqqpyMy+Yeub8dUp3Zt6LlOPqbr/60erwuyujkDSUe9RurWI3F7TT7szlTJyWHmRbLsXMsTmVud6vNxXj9xi+CEU25gCoDxEqip7PaLYTAoSKvMIbefE+fz7WOSs3WpdOqP6OSoi5Ury58DYwRLQDDNElll33bH7xGit/4+kP3FG66xsPNy2sYeK6bneXwrdFVGtBcjBP8LUxRkkOCaXvMBfbqTQioQYlKhyGiRHz7NPSQzm+d053fvpQlUezvxml1SGsoYlTTI4f3LGl3vgGHpa+bwVLuLxQMiPihWsBy6ljgvw0qGV8zJnvnj0u0zjnasUP+WRodDYPUtN4z1aGyABMiHRH4XKPBNiyrPtXMrL1SHPB5QJWuhy4Jv/ci3HiSrJMc=
  - secure: GiFCRSPJi6t3A3O0MP1FMS1wtGcaES68lp0WNR76K7NOOxwCWXIQ8k4aCaH01+VgJoglpyaPoqI1gZnVsbWVXa8luR1oRYlHAmMsmihSHvUx6FloBUL+oyiBAkGzjFJRc4pYVHCp1FYvH79neHtKFm0gz2g/S0i6unCvsa7lTteF7xFgF5p7iyA1OeHnH6rU1g0j2UH/n2P6CuOeQzrfksrg0aLLqqJ0yzK+F61IZQGHfSIgJk5BDggDhqPDU8rWjm6TIyXBf1Y4D79wqZ0bneXwsalnEfaYiMQT9eS14U3I30Y+bobPUWCbDDKxYOt96NmncRC//fuks6nyfTHNUPqIebUAdSypJ1CgrTCcPIKYT/5x/quSuedpf9BfmRdaWeNNHz2wMU8vIV7SOIU5d8AoEtl9Of8yj58+Q1Mck76Dr5FaSae2oP6auqB7K5NJz+91GpZazosn2fVXPkTg4smQ00aPNVwdOvZwCIGeEBCrCdBjfjqrnSClvIBEF3eoaNMWlmNZwy/dsYaI76VFcbOBt6OUWAf/IlwLHkwAjR0GoFyT8Y0n32xliJTQwgIf/yIDzF23346MUgorAzVMed6BEv2vDa6EFNPJCegvxCHznLV0h6eskv9nGCLJvKrty8FCJPacZg7UqzbTK5dQAYqE+Wz+9qg0FqDHwysKPLU=
